Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Group41_Wired_Martians.Areas.Identity.Data;
using Group41_Wired_Martians.Models;
using Newtonsoft.Json;

namespace Project.Controllers
{
    public class CategoryController : Controller
    {
        private readonly AppDbContext _context;

        public CategoryController(AppDbContext context)
        {
            _context = context;

        }
  
        public async Task<IActionResult> Index()
        {
            var Categ = _context.Categories;
            return View(await Categ.ToListAsync());
        }
        public async Task<ActionResult> AddandEdit(int? id)
        {
            if (id == null)
            {
                return View(new Category());
            }
            var category = await _context.Categories.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddandEdit(int id, [Bind("CategoryID,CategoryName,Description,ImageURL", "CreatedDate", "ModifiedDate", "Status")] Category category)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (id == 0)
                    {
                        _context.Add(category);

                    }
                    else
                    {
                        _context.Update(category);
                    }

                    await _context.SaveChangesAsync();
                    return Json(new { success = true, message = "Category saved successfully." });
                }
                catch (Exception )
                {
                    // Set error message
                    TempData["ErrorMessage"] = "An error occurred while saving the category.";
                }

            }
            else
            {
                // Set failure message
                TempData["FailureMessage"] = "Failed to add or update category. Please correct the errors and try again.";
            }
            return Json(new { success = false, message = "Failed to save Category." });
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.CategoryID == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var category = await _context.Categories.FindAsync(id);
            if (category != null)
            {
                category.Status = "Inactive";
                _context.Update(category);
                await _context.SaveChangesAsync();

            }

            return RedirectToAction(nameof(Index));
        }

    }
}

Controllers/CustomerController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Group41_Wired_Martians.Areas.Identity.Data;
using Group41_Wired_Martians.Models;

namespace Group41_Wired_Martians.Controllers
{
    public class CustomerController : Controller
    {
        private readonly AppDbContext _context;

        public CustomerController(AppDbContext context)
        {
            _context = context;

        }
        public async Task<IActionResult> AllCustomers()
        {
            var Customer = _context.Customers;
            return View(await Customer.ToListAsync());


        }
        public async Task<ActionResult> CreateCustomer(int? id)
        {
            if (id == null)
            {
                return View(new Customer());
            }
            var Customers = await _context.Customers.FindAsync(id);
            if (Customers == null)
            {
                return NotFound();
            }

            return View(Customers);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateCustomer(int id, Customer customer)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    customer.Avatar = "/Images/Profile-Avatars/Profile3.jpg";
                    if (id == 0)
                    {
                        _context.Add(customer);

                    }
                    else
                    {
                        _context.Update(customer);
                    }

                    await _context.SaveChangesAsync();
                    return Json(new { success = true, message = "Customer Added successfully." });
                }
                catch (Exception)
                {
                    return Json(new { success = false, message = "An error occurred while saving the customer." });
                }

            }
            else
            {
                return Json(new { success = false, message = "Failed to save Customer." });
            }
   
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.Customers
                .FirstOrDefaultAsync(m => m.CustomerID == id);
            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var Customer = await _context.Customers.FindAsync(id);
            if (Customer != null)
            {
                Customer.Status = "Inactive";
                _context.Update(Customer);
                await _context.SaveChangesAsync();

            }

            return RedirectToAction(nameof(AllCustomers));
        }
    }
}

Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Group41_Wired_Martians.Areas.Identity.Data;
using Group41_Wired_Martians.Models;
using Group41_Wired_Martians.viewmodels;
using Newtonsoft.Json;

namespace Project.Controllers
{
    public class ProductController : Controller
    {
        private readonly IWebHostEnvironment _hostEnvironment;
        private readonly AppDbContext _context;

        public ProductController(IWebHostEnvironment hostEnvironment, AppDbContext context)
        {
            _hostEnvironment = hostEnvironment;
            _context = context;

        }
      
        public async Task<IActionResult> ProductList()
        {
            var ProductList = _context.Products.Include(c => c.Category).Include(c => c.Supplier);
            return View(await ProductList.ToListAsync());


        }
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.Category)
                .FirstOrDefaultAsync(m => m.ProductID == id);

            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        public async Task<ActionResult> AddandEdit(int? id)
        {
       
            var supplier = await _context.Suppliers.ToListAsync();
            ViewData["SupplierID"] = new SelectList(supplier, "SupplierID", "SupplierName");

            var categories = await _context.Categories.ToListAsync();
            ViewData["CategoryID"] = new SelectList(categories, "CategoryID", "CategoryName");

            if (id == null)
            {
                return View(new Product());
            }
            var product = await _context.Products
                                .FirstOrDefaultAsync(p => p.ProductID == id);
            if (product == null)
            {
                return NotFound();
            }
            ViewData["CategoryID"] = new SelectList(_context.Categories, "CategoryID", "CategoryName", product.CategoryID);

            ViewData["SupplierID"] = new SelectList(_context.Suppliers, "SupplierID", "SupplierName", product.SupplierID);
            return View(product);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddandEdit(int id, Product product)
        {

            if (ModelState.IsValid)
            {
                try
                {

                    if (product.ImageFile1 != null)
                    {
                        try
                        {
                            string wwwRootPath = _hostEnvironment.WebRootPath;
                            string fileName = Path.GetFileNameWithoutExtension(product.ImageFile1.FileName);
                            string extension = Path.GetExtension(product.ImageFile1.FileName);
                            product.ImgThumbnail = fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                            string path = Path.Combine(wwwRootPath + "/images/", fileName);
                            using (var fileStream = new FileStream(path, FileMode.Create))
                            {
                                await product.ImageFile1.CopyToAsync(fileStream);
                            }
                        }
                        catch (Exception ex)
                        {
                            TempData["ErrorMessage"] = "An error occurred while uploading the first image.";
                            Console.WriteLine($"Exception: {ex.Message}, StackTrace: {ex.StackTrace}");
                            return Json(new { success = false, message = "Failed to upload first image." });
                        }
                    }

                    if (product.ImageFile2 != null)
                    {
                        try
                        {
                            string wwwRootPath = _hostEnvironment.WebRootPath;
                            string fileName = Path.GetFileNameWithoutExtension(product.ImageFile2.FileName);
                            string extension = Path.GetExtension(product.ImageFile2.FileName);
                            product.ImageFile = fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                            string path = Path.Combine(wwwRootPath + "/images/", fileName);
                            using (var fileStream = new FileStream(path, FileMode.Create))
                            {
                                await product.ImageFile2.CopyToAsync(fileStream);
                            }
                        }
                        catch (Exception ex)
                        {
                            TempData["ErrorMessage"] = "An error occurred while uploading the second image.";
                            Console.WriteLine($"Exception: {ex.Message}, StackTrace: {ex.StackTrace}");
                            return Json(new { success = false, message = "Failed to upload second image." });
                        }
                    }


                    var existingProduct = await _context.Products
                   .FirstOrDefaultAsync(p => p.ProductID == id);

                    

                    if (existingProduct != null)
                    {
                        _context.Entry(existingProduct).CurrentValues.SetValues(product);
                        _context.Update(existingProduct);
                    }
                    else
                    {

                        _context.Add(product);
                    }

                    await _context.SaveChangesAsync();

                    return Json(new { success = true, message = "Product saved successfully." });

                }
                catch (Exception ex)
                {
                    TempData["ErrorMessage"] = "An error occurred while saving the product.";
                    Console.WriteLine($"Exception: {ex.Message}, StackTrace: {ex.StackTrace}");
                }

            }
            else
            {
                foreach (var modelStateKey in ModelState.Keys)
                {
                    var modelStateVal = ModelState[modelStateKey];
                    foreach (var error in modelStateVal.Errors)
                    {
                       
                        Console.WriteLine($"Key: {modelStateKey}, Error: {error.ErrorMessage}");
                    }
                }

                TempData["FailureMessage"] = "Failed to add or update product. Please correct the errors and try again.";
            }
            ViewData["CategoryID"] = new SelectList(await _context.Categories.ToListAsync(), "CategoryID", "CategoryName", product.CategoryID);

            ViewData["SupplierID"] = new SelectList(await _context.Suppliers.ToListAsync(), "SupplierID", "SupplierName", product.SupplierID);

            return Json(new { success = false, message = "Failed to save product." });
        }

   
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .FirstOrDefaultAsync(m => m.ProductID == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteProduct(int id)
        {
            var product = await _context.Products.FindAsync(id);
            if (product != null)
            {
                product.Status = "Inactive";
                _context.Update(product);
                await _context.SaveChangesAsync();

            }

            return RedirectToAction(nameof(ProductList));
        }
    }
}

Controllers/StockLiasonController.cs
using Group41_Wired_Martians.Areas.Identity.Data;
using Group41_Wired_Martians.Models;
using Group41_Wired_Martians.viewmodels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Group41_Wired_Martians.Controllers
{
    public class StockLiasonController : Controller
    {
        private readonly AppDbContext _context;
        private readonly RoleManager<IdentityRole> _roleManager;
        public StockLiasonController(AppDbContext context, RoleManager<IdentityRole> roleManager)
        {
            _context = context;
            _roleManager = roleManager;
        }
        public async Task<IActionResult> DashBoard()
        {
      

            var inventories = await _context.Inventories
        .Include(i => i.Product)
        .Include(i => i.ProductColors)
        .ToListAsync();

            var products = await _context.Products.Include(c => c.Category).Include(s => s.Supplier).ToListAsync();

            var productscount = await _context.Products.CountAsync();
            ViewBag.Productscount = productscount;

            var customers = await _context.Customers
                .OrderByDescending(c => c.CustomerID)
                .ToListAsync();

            var activeemployees = await _context.Customers.Where(c => c.Status == "Active").CountAsync();

            ViewBag.ActiveCustomerCount = activeemployees;

            var viewModel = new DashboardViewmodel
            {
                Inventories = inventories,
                Customers = customers,
                Products = products,
               
            };

            return View(viewModel);
        }

    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Group41_Wired_Martians</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Group41_Wired_Martians.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Group41_Wired_Martians</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
            <partial name="_LoginPartial.cshtml" />
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Group41_Wired_Martians - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_StockLiason.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Wired Martians</title>

    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/css/bootstrap.min.css" rel="stylesheet">
    
    <!-- SweetAlert CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />

    <!-- Custom CSS -->
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/StockLiason.css" asp-append-version="true" />
    <style>

        #sidebar {
            position: fixed;
            top: 0;
            left: 0;
            width: 280px;
            height: 100%;
            background: var(--light);
            z-index: 2000;
            font-family: var(--lato);
            transition: .3s ease;
            overflow-x: hidden;
            scrollbar-width: none;
        }

            #sidebar.hide {
                width: 60px;
            }

                #sidebar.hide #content {
                    width: calc(100% - 60px);
                    left: 60px;
                }
    </style>
</head>
<body>
    <div>
        <div id="sidebar">
            <div class="brand">
                <a href="#">
                    <img class="Logo-main" src="~/images/logo.png" />
                </a>
                <a href="#" class="nav__logo">Martian Collers</a>
            </div>
            <div class="l-navbar">
                <side class="side">
                    <div class="nav__list">
                        <a href="@Url.Action("Dashboard", "StockLiason" )" id="dashboard-link" class="nav__link">
                            <ion-icon name="albums-outline" class="nav__icon"></ion-icon>
                            <span class="nav__name">DashBoard</span>
                        </a>
                        <div class="nav__link Collapselink">
                            <ion-icon name="people-outline" class="nav__icon"></ion-icon>
                            <span class="nav__name">Customers</span>

                            <ion-icon name="chevron-down-outline" class="collapse__link"></ion-icon>

                            <ul class="collapse__menu">
                                <a href="@Url.Action("CreateCustomer","Customer")" class="collapse__sublink">Manange</a>
                                <a href="@Url.Action("AllCustomers","Customer")" class="collapse__sublink">CustomerList</a>
                            </ul>
                        </div>
                        <a href="@Url.Action("Index", "Category" )" class="nav__link ">
                            <ion-icon name="folder-outline" class="nav__icon"></ion-icon>
                            <span class="nav__name">Categories</span>
                        </a>
                        <div class="nav__link Collapselink">
                            <ion-icon name="scan-outline" class="nav__icon"></ion-icon>
                            <span class="nav__name">Product Manange</span>

                            <ion-icon name="chevron-down-outline" class="collapse__link"></ion-icon>
                            <ul class="collapse__menu">
                                <a href="@Url.Action("AddandEdit", "Product" )" class="collapse__sublink">NewProduct</a>
                                <a href="@Url.Action("ProductList", "Product" )" class="collapse__sublink">ProductList</a>
                            </ul>
                        </div>
                        <a href="@Url.Action("Create", "Inventory" )" class="nav__link">
                            <ion-icon name="pie-chart-outline" class="nav__icon"></ion-icon>
                            <span class="nav__name">Inventory</span>
                        </a>
                        <div class="nav__link Collapselink">
                            <ion-icon name="cash-outline" class="nav__icon"></ion-icon>
                            <span class="nav__name">Allocations</span>
                            <ion-icon name="chevron-down-outline" class="collapse__link"></ion-icon>
                            <ul class="collapse__menu">
                                <a href="@Url.Action("Create","FridgeAllocation")" class="collapse__sublink">New</a>
                                <a href="@Url.Action("Index","FridgeAllocation")" class="collapse__sublink">LIST</a>
                            </ul>
                        </div>
                        <a href="#" class="nav__link">
                            <ion-icon name="hammer-outline" class="nav__icon"></ion-icon>
                            <span class="nav__name">Scrapped</span>
                        </a>
                        <a href="#" class="nav__link">
                            <ion-icon name="settings-outline" class="nav__icon"></ion-icon>
                            <span class="nav__name">Settings</span>
                        </a>
                        <a href="#" class="nav__link">
                            <ion-icon name="log-out-outline" class="nav__icon"></ion-icon>
                            <span class="nav__name">Log Out</span>
                        </a>
                    </div>
                </side>
            </div>
        </div>
        <div id="content">
            <nav>
                <div class="nav__brand">
                    <ion-icon name="menu-outline" class="nav__toggle" id="nav-toggle"></ion-icon>
                </div>
                <form action="#">
                    <div class="form-input">
                        <input type="search" placeholder="Search...">
                        <button type="submit" class="search-btns"><ion-icon name="search-outline"></ion-icon></button>
                    </div>
                </form>

                <div id="clock">Loading...</div>
                <input type="checkbox" id="switch-mode" hidden>
                <label for="switch-mode" class="switch-mode"></label>
                <a href="#" class="notification-up">
                    <ion-icon name="notifications-outline"></ion-icon>
                    <span class="num">8</span>
                </a>
                <a href="#" class="profile">
                    <img src="https://t3.ftcdn.net/jpg/05/16/27/58/360_F_516275801_f3Fsp17x6HQK0xQgDQEELoTuERO4SsWV.jpg">
                </a>
            </nav>
            <div>
                <main role="main" class="main">
                    @RenderBody()
                </main>
            </div>
        </div>
    </div>
    

  
    <div id="loader" class="loader" style="display:none;"></div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" crossorigin="anonymous"></script>
    <!-- SweetAlert JS -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>


    <!-- Ionicons -->
    <script type="module" src="https://unpkg.com/ionicons@5.1.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule="" src="https://unpkg.com/ionicons@5.1.2/dist/ionicons/ionicons.js"></script>

    <!-- Custom JS -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/StockLiason.js" asp-append-version="true"></script>
  
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>